### ISSUE TITLE
Split Library into multiple Modules

### ISSUE THREAD

**Issue by jbee** [jbee/silk#104]
The library is already build with modularity in mind.
In effect it already has modules that build upon each other. 
But this is currently not reflected as java modules.

Modules that should be extracted:

1. base API (might be used in application user code if user chooses to): `se.jbee.inject`
2. declaration API (only used in bundle/module code) [needs 1.]: `se.jbee.inject.config` + `se.jbee.inject.extend` + `se.jbee.inject.declare` + `se.jbee.inject.bind`
3. the core implementation [needs 1. + 2.]: `se.jbee.inject.scope` + `se.jbee.inject.container`
Some classes might need to be moved to allow splitting into an API and an core implementation so that the API contains all classes needed by the user. A 3rd module might be needed to contain those classes that are essential to both user API and implementation
4. bootstrapping API: `se.jbee.inject.bootstrap` (this is only used at a single point in an application)

Further this basis can be extended with further feature packages [each need 1-3]:

5. actions: `se.jbee.inject.action`
6. events: `se.jbee.inject.event`
7. type converters: `se.jbee.inject.convert`

**Comment by jbee** [comment]
@sormuras This is a task for us soon ;)

**Comment by sormuras** [comment]
Looking forward to it.

**Comment by sormuras** [comment]
Do already have names for the Java modules in your mind?

### module se.jbee.inject

Exports package
- `se.jbee.inject`

Requires module
- `java.base`

### module se.jbee.inject.api

Exports package
- `se.jbee.inject.config`
- `se.jbee.inject.extend`
- `se.jbee.inject.declare`
- `se.jbee.inject.bind`

Requires module
- `java.base`
- `se.jbee.inject`

...

**Comment by jbee** [comment]
@sormuras did update once again with the bootstrap module - now the dependencies look fine to me (and I think the packages already have these interdependencies)

**Comment by jbee** [comment]
Done by #112
