### ISSUE TITLE
Group modules in API documentation

### ISSUE THREAD

**Issue by sormuras** [jbee/silk#117]
#### Status

![image](https://user-images.githubusercontent.com/2319838/89627255-dea2dd00-d89a-11ea-9774-9c3de4218b16.png)

#### Groups

- **API** _all others_
- **Container** `container`, `bootstrap`
- **Add-ons** `event`, `action`, `convert`

**Comment by sormuras** [comment]
### API

![image](https://user-images.githubusercontent.com/2319838/89628801-1f035a80-d89d-11ea-9541-f2780b79a997.png)

### Container

![image](https://user-images.githubusercontent.com/2319838/89628878-393d3880-d89d-11ea-8638-fc25596cecf3.png)

### Add-ons

![image](https://user-images.githubusercontent.com/2319838/89628962-5540da00-d89d-11ea-8a27-709d295aa186.png)

**Comment by jbee** [comment]
Nice!
