### ISSUE TITLE
Support Silk as JUnit 5 extension

### ISSUE THREAD

**Issue by sormuras** [jbee/silk#66]
Something similar to http://weld.cdi-spec.org/news/2017/12/19/weld-meets-junit5/ :)

**Comment by jbee** [comment]
To do what exactly?

**Comment by jbee** [comment]
@sormuras I need more details on the goal of your suggestion.

**Comment by sormuras** [comment]
> To do what exactly?

You're right. Thought about some days ... and still don't have a use-case. Thus, closing this issue.

**Comment by jbee** [comment]
FYI: Silk already has great JUnit support since it does not need any special runner or extension. Look at all the tests of the library. Its all pain JUnit tests and works just fine to verify or use the context in tests.

**Comment by sormuras** [comment]
I fully agree.

Scanned the sources briefly and two thoughts popped up:
-Interested in migrating to JUnit 5, starting with Vintage for all existing tests and using Jupiter for new tests?
- What about a module descriptor for Silk? Are the internal packages that you want to hide?

Happy to open related feature requests and helping implementing them.

**Comment by jbee** [comment]
**Tests** I didn't feel any pressure to migrate to JUnit 5 but I am also not against it. So far I had no pain points with 4 as I am just using the basics most of the time. Do you see advantages of 5 that apply to the existing tests or make unit test "better" (mostly I am after simple, reliable) compared to 4?

**Modules** I just moved numerous classes around as I am implementing the more advanced configuration (fully customisable and `ServiceLoader` friendly - think "automatic pickup and assembly") to move towards a better integration and out of the box experience in web-containers while keeping the simplicity of the programmatic setup as the basis. Generally I tend to use visibility modifiers to hide classes, methods and fields that I want hidden and organise the code-base so it is possible to hide types that belong hidden. Then I use STAN to check I got no circles. Currently the dependencies between the packages (and I consider those modules) look like these
![modules](https://user-images.githubusercontent.com/309438/76681963-36912c80-65f8-11ea-9c28-6f8210a8e330.png)
With modules the root package and each of its direct sub-packages could become a own module which build on each other. But to start the full lib could also just be one module exporting everything that is visible. PRs are always welcome. We can discuss details in the particular PRs.

In that context I also thinking about migration to maven. Not that I like it better but the ant support further down the tool-chain gets worse by the day. In particular setting up sonar keep causing headaches. As the lib is dependency free and very simple the standard single module maven setup should do. If you want to contribute in that area this would also be highly appreciated.

**Comment by sormuras** [comment]
I'll update my fork...

![image](https://user-images.githubusercontent.com/2319838/76682387-106d8b80-65fc-11ea-98cb-d8bc0fa30e9e.png)

...and see, what I can come up with.
