### ISSUE TITLE
Construction Error Recovery

### ISSUE THREAD

**Issue by jbee** [jbee/silk#76]
When application is bootstrapped and instances get constructed and injected the construction might throw an exception and fail. Such problem would propagate upwards and fail the whole bootstrapping process. Sometimes this is not what maintainers would want to happen - instead if would be preferable having the part fail to bootstrap (and cause runtime errors later on where the part was supposed to be used) but have the whole bootstrapping complete successful. 

For this to work the container needs to be aware if and where exceptions during construction should be recovered and instead injected as null or with some other default.

**Comment by automenta** [comment]
maybe it could expect failure as a specific 'ambiguous' state containing the known missing or conflicting data.  a user could then interactively resolve these dynamically either through code changes or a UI with autogenerated widgets to help disambiguate to valid models.  maybe something like this already exists in the code, i didnt look carefully but this issue is the closest thing.  ive been wanting a smart dynamic DI container that works like that and silk seems capable of it

**Comment by jbee** [comment]
@automenta I'm not sure if silk container is what you are looking for. It is intentionally not dynamic in the sense that the full mapping must be given at bootstrapping. No mappings can be added or removed later on. That does not mean that it cannot show behaviour that occurs to be _dynamic_, just like the described error recovery, but such behaviour would need to be mapped before hand and not on the basis of how the bootstrapping went so far. This is so the container stays predictable for the developers. Because of this design a wide range of mappings are supported that give very detailed control over when a mapping applies. 

The idea with the error recovery was that I could extend the types of mapping adding a _FALLBACK_ type that would specifically be used when another mapping that usually would be used fails to construct the instance.

**Comment by automenta** [comment]
yes it would involve a loss of predictability - the reasons are better explained in these incomplete prototypes:
https://github.com/automenta/objenome
https://github.com/automenta/objenome_prototype
:joystick:

**Comment by jbee** [comment]
The first thing that comes to mind reading _automated assembly_ is require & provide in silk. These are mapping types. _Provide_ "says", look I know how to provide X so ask me if that is what is needed while require expresses the need of a particular component, e.g. X where X can be narrowed by java relevant properties like the interface it implements, the package, parent or target instance. This allows to build loosely coupled _modules_ that assemble together without knowing each other based on the contracts used to bind them together.

Now, is there any particular scenario you want to solve that you want me to comment on?

**Comment by jbee** [comment]
After looking at your example it might be that you are mostly just looking for the way bundles and modules work in silk where you can describe assembly locally and later compose apps by composing module descriptions. The only difference is that everything is deterministic in silk. Its like functional programming where you describe how you want your universe to be defined. Silk then makes that happen.

**Comment by automenta** [comment]
it makes sense to use the deterministic components you refer to for a non-deterministic API...  unless there's a benefit to representing the non-deterministic parameters (if any) in the same model as the deterministic configuration. ex: to allow changes between determinstic and non-deterministic (which is the approach in my prototypes).

mainly i was wondering if you or anyone else have interest in something like this semi-wired state that can be iteratively disambiguated (or re-ambiguated).  ex: as abstract branch point for non-interactive program evolution, objective optimization, etc.. or as a GUI form generator for prompting a user for providable data.

if theres anything i can explain ill be glad to otherwise this is not urgent

thanks

**Comment by automenta** [comment]
in general. but the two incomplete prototypes i linked to could be considered a proof of the concept

**Comment by jbee** [comment]
I am afraid you're kind of asking the wrong person. I made silk because of the unpredictable, deeply frustrating and limited nature of existing DI containers. Having a semi-wired state must be somewhere on the opposite end of what I would want to have. 

Maybe Paul Phillips has some useful advice for you https://youtu.be/TS1lpKBMkgg?t=1701

**Comment by automenta** [comment]
thanks for clarifying your opinion.  this advice isnt relevant to the use cases i'm interested in

**Comment by jbee** [comment]
Take it as general advice on design. It kind of always applies.

**Comment by automenta** [comment]
```
        Multitainer g = new Multitainer();
        g.any(Part.class, of(Part0.class, Part1.class, PartN.class));                     
        g.any(OtherPart.class, of(OtherPart0.class, OhterPart1.class));                     
        g.is("floatField", in(0, 3.14159));
        Objenome o = g.random(Machine.class);    
        Machine m = o.get(Machine.class);
```
this doesnt build a specific solution but a space of solutions that a search process can sample from.  silk seems flexible enough that if it doesnt already somehow support these semantics in its metamodel, it could be extended to. but the same is true for nearly every other dynamic DI framework.

**Comment by jbee** [comment]
Yes, you could add a few bits and practically be there. Do you want advice on how to modify silk?

**Comment by jbee** [comment]
Deleted a conversation that was off-topic for this issue.

**Comment by jbee** [comment]
This can be done in a similar way optionals are working. However, for arrays that are composed of many resources one would like to recover/skip those that fail getting just those that succeed injected.

```java
interface Obtainable<T> {
  T obtain();
}
```
Should T be an 1-dimensional array type it tries to resolve resources for that element type and assembles the array from those succeeding.

**Comment by jbee** [comment]
Resolved by adding `Obtainable` as a installable core feature in #120. Similar error recovery mechanisms equally can be build in user space.
