### ISSUE TITLE
Invalid use of a restricted identifier `yield`

### ISSUE THREAD

**Issue by sormuras** [jbee/silk#78]
Found another `yield` method

https://github.com/jbee/silk/blob/25426965253062d0238e2db97b19175f042892a7/src/core/se/jbee/inject/container/InjectionSite.java#L92

Yields (pun intended):

```text
src\core\se\jbee\inject\container\InjectionSite.java:56: error: invalid use of a restricted identifier 'yield'
				: yield(generators[i], site.instanced(hint.relativeRef));
				  ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
src\core\se\jbee\inject\container\InjectionSite.java:80: error: invalid use of a restricted identifier 'yield'
					preResolvedArgs[i] = yield(resource,
					                     ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
2 errors
```

See https://github.com/jbee/silk/pull/77#discussion_r393860959 -- rename it to `generate` as well?

**Comment by jbee** [comment]
> rename it to generate as well?

yes, please

**Comment by sormuras** [comment]
Erm, closed too early. Failed to target this origin with the PR...
