### ISSUE TITLE
Refactor away from getCanonicalName() to...

### ISSUE THREAD

**Issue by sormuras** [jbee/silk#81]
https://github.com/jbee/silk/blob/9217d612a0c9aac7607f98333506b9c98094e618/src/core/se/jbee/inject/Type.java#L432-L437

...somthing with better handling `null` names https://github.com/sormuras/silk/pull/2#issuecomment-636096996:

> Generally update tests - however, if this is the result of Type.toString() the output should not change. In that case the method implementation needs to be adopted so it uses getName() but does special handling for arrays (and maybe also primitives). Anyhow, this is hardly your job so its fine to just ignore the tests and make a common why they need fixing - I can do that later.

**Comment by jbee** [comment]
Addressed by #103
